!!!!Credit Risk Data Challenge!!!                                                                  
A Learner project with RandomForestRegressor.

In [49]:
root="C:\\Users\\Apurva\\Downloads\\courses\\credit-risk-challenge\\data\\application_train"
root_b = "C:\\Users\\Apurva\\Downloads\\courses\\credit-risk-challenge\\data\\bureau"
root_cc = "C:\\Users\\Apurva\\Downloads\\courses\\credit-risk-challenge\\data\\credit_card_balance"

Let's load the main data file!!!

In [50]:
import pandas as pd

#This is our main data-set file. We need to join this 
#main dataframe with other dataframes to get more features.
master = open( root + "\\application_train.csv",'r')

fields = ['SK_ID_CURR','TARGET','NAME_CONTRACT_TYPE','CODE_GENDER','FLAG_OWN_CAR','FLAG_OWN_REALTY'
          ,'CNT_CHILDREN','AMT_INCOME_TOTAL','AMT_CREDIT','AMT_ANNUITY','AMT_GOODS_PRICE',
          'NAME_TYPE_SUITE','NAME_INCOME_TYPE','NAME_EDUCATION_TYPE','NAME_FAMILY_STATUS',
          'NAME_HOUSING_TYPE','REGION_POPULATION_RELATIVE','DAYS_BIRTH','DAYS_EMPLOYED'
          ,'DAYS_REGISTRATION','DAYS_ID_PUBLISH','OWN_CAR_AGE','FLAG_PHONE','OCCUPATION_TYPE',
          'CNT_FAM_MEMBERS','REGION_RATING_CLIENT','REGION_RATING_CLIENT_W_CITY',
          'REG_CITY_NOT_LIVE_CITY','REG_CITY_NOT_WORK_CITY','ORGANIZATION_TYPE',
          'LIVE_CITY_NOT_WORK_CITY','APARTMENTS_AVG','BASEMENTAREA_AVG',
          'YEARS_BEGINEXPLUATATION_AVG','YEARS_BUILD_AVG','EXT_SOURCE_1','EXT_SOURCE_2'
           ,'EXT_SOURCE_3', 'AMT_REQ_CREDIT_BUREAU_YEAR','YEARS_BEGINEXPLUATATION_AVG',
          'APARTMENTS_AVG','YEARS_BUILD_AVG','COMMONAREA_AVG','ELEVATORS_AVG','YEARS_BUILD_MODE',
          'APARTMENTS_MEDI','YEARS_BEGINEXPLUATATION_MEDI','LANDAREA_MEDI','AMT_REQ_CREDIT_BUREAU_HOUR',
          'AMT_REQ_CREDIT_BUREAU_DAY','AMT_REQ_CREDIT_BUREAU_WEEK','AMT_REQ_CREDIT_BUREAU_MON',
          'AMT_REQ_CREDIT_BUREAU_QRT']

df = pd.read_csv(master, usecols=fields) # load application_train.csv in dataframe


Convert every feature to a number!!!

In [51]:
import numpy as np
#function to transfer non numeric fields to numeric fields
def initital_cleaning(df):
    df.replace(np.nan, 0, inplace=True)
    print(df['NAME_CONTRACT_TYPE'].unique())
    print(df['CODE_GENDER'].unique())
    print(df['FLAG_OWN_CAR'].unique())
    print(df['FLAG_OWN_REALTY'].unique())
    print(df['NAME_TYPE_SUITE'].unique())
    print(df['NAME_INCOME_TYPE'].unique())
    print(df['NAME_EDUCATION_TYPE'].unique())
    print(df['NAME_FAMILY_STATUS'].unique())
    print(df['NAME_HOUSING_TYPE'].unique())
    print(df['OCCUPATION_TYPE'].unique())
    print(df['ORGANIZATION_TYPE'].unique())
    
    df['NAME_CONTRACT_TYPE'] = df['NAME_CONTRACT_TYPE'].map({0: 0, 'Cash loans': -1, 'Revolving loans': 1})
    df['CODE_GENDER'] = df['CODE_GENDER'].map({0: 0, 'M': -1, 'F': 1, 'XNA': 0})
    df['FLAG_OWN_CAR'] = df['FLAG_OWN_CAR'].map({0: 0, 'N': 1, 'Y': -1})
    df['FLAG_OWN_REALTY'] = df['FLAG_OWN_REALTY'].map({0: 0, 'N': 1, 'Y': -1})
    df['NAME_TYPE_SUITE'] = df['NAME_TYPE_SUITE'].map({0: 0, 'Unaccompanied': 1, 'Family': 2
                                                          , 'Spouse, partner': 3, 'Children': 4, 'Other_A': 5,
                                                       'Other_B': 6, 'Group of people': 7})
    df['NAME_INCOME_TYPE'] = df['NAME_INCOME_TYPE'].map(
        {'Working': 1, 'State servant': 2, 'Commercial associate': 3, 'Pensioner': 4, 'Unemployed': 5,
         'Student': 6, 'Businessman': 7, 'Maternity leave': 8})
    df['NAME_EDUCATION_TYPE'] = df['NAME_EDUCATION_TYPE'].map(
        {'Secondary / secondary special': 1, 'Higher education': 2, 'Incomplete higher': 3,
         'Lower secondary': 4, 'Academic degree': 5})
    df['NAME_FAMILY_STATUS'] = df['NAME_FAMILY_STATUS'].map(
        {'Single / not married': 1, 'Married': 2, 'Civil marriage': 3, 'Widow': 4, 'Separated': 5,
         'Unknown': 6})
    df['NAME_HOUSING_TYPE'] = df['NAME_HOUSING_TYPE'].map({'House / apartment': 1, 'Rented apartment': 2, 'With parents': 3,
                                                           'Municipal apartment': 4, 'Office apartment': 5,
                                                           'Co-op apartment': 6})
    df['OCCUPATION_TYPE'] = df['OCCUPATION_TYPE'].map(
        {'Laborers': 1, 'Core staff': 2, 'Accountants': 3, 'Managers': 4, 0: 0, 'Drivers': 5,
         'Sales staff': 6, 'Cleaning staff': 7, 'Cooking staff': 8, 'Private service staff': 9,
         'Medicine staff': 10, 'Security staff': 11, 'High skill tech staff': 12,
         'Waiters/barmen staff': 13, 'Low-skill Laborers': 14, 'Realty agents': 15, 'Secretaries': 16,
         'IT staff': 17, 'HR staff': 18})
    df['ORGANIZATION_TYPE'] = df['ORGANIZATION_TYPE'].map(
        {0: 0, 'Business Entity Type 3': 1, 'School': 2, 'Government': 3, 'Religion': 4, 'Other': 5, 'XNA': 6,
         'Electricity': 7, 'Medicine': 8, 'Business Entity Type 2': 9, 'Self-employed': 10,
         'Transport: type 2': 11, 'Construction': 12, 'Housing': 13, 'Kindergarten': 14,
         'Trade: type 7': 15, 'Industry: type 11': 16, 'Military': 17, 'Services': 18,
         'Security Ministries': 19, 'Transport: type 4': 20, 'Industry: type 1': 21, 'Emergency': 22,
         'Security': 23, 'Trade: type 2': 24, 'University': 25, 'Transport: type 3': 26, 'Police': 27,
         'Business Entity Type 1': 28, 'Postal': 29, 'Industry: type 4': 30, 'Agriculture': 31,
         'Restaurant': 32, 'Culture': 33, 'Hotel': 34, 'Industry: type 7': 35, 'Trade: type 3': 36,
         'Industry: type 3': 37, 'Bank': 38, 'Industry: type 9': 39, 'Insurance': 40, 'Trade: type 6': 41,
         'Industry: type 2': 42, 'Transport: type 1': 43, 'Industry: type 12': 44, 'Mobile': 45,
         'Trade: type 1': 46, 'Industry: type 5': 47, 'Industry: type 10': 48, 'Legal Services': 49,
         'Advertising': 50, 'Trade: type 5': 51, 'Cleaning': 52, 'Industry: type 13': 53,
         'Trade: type 4': 54, 'Telecom': 55, 'Industry: type 8': 56, 'Realtor': 57, 'Industry: type 6': 58})
    
    print(df['NAME_CONTRACT_TYPE'].unique())
    print(df['CODE_GENDER'].unique())
    print(df['FLAG_OWN_CAR'].unique())
    print(df['FLAG_OWN_REALTY'].unique())
    print(df['NAME_TYPE_SUITE'
             ''].unique())
    print(df['NAME_INCOME_TYPE'].unique())
    print(df['NAME_EDUCATION_TYPE'].unique())
    print(df['NAME_FAMILY_STATUS'].unique())
    print(df['NAME_HOUSING_TYPE'].unique())
    print(df['OCCUPATION_TYPE'].unique())
    print(df['ORGANIZATION_TYPE'].unique())
    return df
    
print(df['TARGET'].unique())
df = initital_cleaning(df)

[1 0]


['Cash loans' 'Revolving loans']
['M' 'F' 'XNA']
['N' 'Y']
['Y' 'N']
['Unaccompanied' 'Family' 'Spouse, partner' 'Children' 'Other_A' 0
 'Other_B' 'Group of people']
['Working' 'State servant' 'Commercial associate' 'Pensioner' 'Unemployed'
 'Student' 'Businessman' 'Maternity leave']
['Secondary / secondary special' 'Higher education' 'Incomplete higher'
 'Lower secondary' 'Academic degree']
['Single / not married' 'Married' 'Civil marriage' 'Widow' 'Separated'
 'Unknown']
['House / apartment' 'Rented apartment' 'With parents'
 'Municipal apartment' 'Office apartment' 'Co-op apartment']
['Laborers' 'Core staff' 'Accountants' 'Managers' 0 'Drivers'
 'Sales staff' 'Cleaning staff' 'Cooking staff' 'Private service staff'
 'Medicine staff' 'Security staff' 'High skill tech staff'
 'Waiters/barmen staff' 'Low-skill Laborers' 'Realty agents' 'Secretaries'
 'IT staff' 'HR staff']


['Business Entity Type 3' 'School' 'Government' 'Religion' 'Other' 'XNA'
 'Electricity' 'Medicine' 'Business Entity Type 2' 'Self-employed'
 'Transport: type 2' 'Construction' 'Housing' 'Kindergarten'
 'Trade: type 7' 'Industry: type 11' 'Military' 'Services'
 'Security Ministries' 'Transport: type 4' 'Industry: type 1' 'Emergency'
 'Security' 'Trade: type 2' 'University' 'Transport: type 3' 'Police'
 'Business Entity Type 1' 'Postal' 'Industry: type 4' 'Agriculture'
 'Restaurant' 'Culture' 'Hotel' 'Industry: type 7' 'Trade: type 3'
 'Industry: type 3' 'Bank' 'Industry: type 9' 'Insurance' 'Trade: type 6'
 'Industry: type 2' 'Transport: type 1' 'Industry: type 12' 'Mobile'
 'Trade: type 1' 'Industry: type 5' 'Industry: type 10' 'Legal Services'
 'Advertising' 'Trade: type 5' 'Cleaning' 'Industry: type 13'
 'Trade: type 4' 'Telecom' 'Industry: type 8' 'Realtor' 'Industry: type 6']


[-1  1]
[-1  1  0]
[ 1 -1]
[-1  1]
[1 2 3 4 5 0 6 7]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[ 1  2  3  4  0  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58]


Randomize and split into 80:20 !!!!!

In [52]:
#AMT_CREDIT_MAX_OVERDUE
bureau = open( root_b + "\\bureau.csv",'r')
overduemap = {}
skip=True
for line in bureau.readlines():
    if skip:
        skip=False
        continue
    s = line.split(',')
    id = int(s[0])
    overdue = 0
    if s[8] is None or s[8] == '':
        continue
    else:
        overdue = float(s[8])
    a=overduemap.get(id,None)
    if a is None:
        overduemap[id] = overdue
    else:
        overduemap[id] = a + overdue

previous = open( root + "\\previous_application.csv",'r')
skip=True
existsmap = {}
refusedmap = {}
refusedtypemap = {}
cancelledmap = {}
cancelledtypemap = {}
for line in previous.readlines():
    if skip:
        skip=False
        continue
    s = line.split(',')
    id = int(s[1])
    status = s[16]
    type = -1
    if s[2] == 'Consumer loans':
        type = 0
    elif s[2] == 'Cash loans':
        type =-1
    elif s[2] == 'Revolving loans':
        type =1
    if status == 'Refused':
        refusedmap[id] = 1
        refusedtypemap[str(id)+str(type)] = 1
    elif status == 'Canceled':
        cancelledmap[id] = 1
        cancelledtypemap[str(id)+str(type)] = 1
    elif status == 'Approved':
        val = refusedmap.get(id, None)
        if val is None:
            refusedmap[id] = -1
    existsmap[id]=1
    
def populate_bureau_features(df):
    overdues = []
    exists = []
    refused = []
    cancelled = []
    refusedtype = []
    cancelledtype = []
    for i, row in df.iterrows():
        value = overduemap.get(df.at[i,'SK_ID_CURR'], -1)
        overdues.append(value)
        id = df.at[i,'SK_ID_CURR']
        type = df.at[i,'NAME_CONTRACT_TYPE']
        key = str(id) + str(type)
        refused.append(refusedmap.get(id, 0))
        cancelled.append(cancelledmap.get(id, 0))
        refusedtype.append(refusedtypemap.get(key, 0))
        cancelledtype.append(cancelledtypemap.get(key, 0))
        exists.append(existsmap.get(id, 0))
        
    df['PREVIOUS_EXISTS'] = exists
    df['REFUSED'] = refused
    df['CANCELLED'] = cancelled
    df['CANCELLED_TYPE'] = cancelledtype
    df['REFUSED_TYPE'] = refusedtype
    df['AMT_CREDIT_MAX_OVERDUE_1'] = overdues
    return df

df = populate_bureau_features(df)

In [53]:
credit_card = open(root_cc + "\\credit_card_balance.csv", 'r')
balancemap = {}
limitmap = {}
atmmap = {}
atmdmap = {}
skip = True
for line in credit_card.readlines():
    if skip:
        skip = False
        continue
    s = line.split(',')
    id = int(s[1])
    balance = 0
    try:
        balance = float(s[3])
    except ValueError:
        balance = 0

    limit = 0
    try:
        limit = float(s[4])
    except:
        limit = 0
    atm = 0
    try:
        atm = float(s[7])
    except:
        atm = 0
    atm_d = 0
    try:
        atm_d = float(s[16])
    except:
        atm_d = 0

    a = limitmap.get(id, None)
    if balance is None or balance == '':
        continue
    if a is None:
        limitmap[id] = limit
        balancemap[id] = balance
        atmmap[id] = atm
        atmdmap[id] = atm_d
    else:
        limitmap[id] = a + limit
        balancemap[id] = balancemap[id] + balance
        atmmap[id] = balancemap[id] + atm
        atmdmap[id] = balancemap[id] + atm_d

print('::Started adding credit card balance to dataframe::')

def populate_credit_card_features(df):
    balanceratio = []
    atmratio = []
    atmdratio =[]
    for i, row in df.iterrows():
        limit = limitmap.get(df.at[i, 'SK_ID_CURR'], 1)
        if limit == 0 or limit == 0.0:
            limit = 1
        balance = balancemap.get(df.at[i, 'SK_ID_CURR'], -1)
        balanceratio.append(balance / limit)
        atmratio.append(atmmap.get(df.at[i, 'SK_ID_CURR'], -1) / limit)
        atmdratio.append(atmdmap.get(df.at[i, 'SK_ID_CURR'], -1) / limit)
    
    df['BALANCE_RATIO'] = balanceratio
    df['ATM_RATIO'] = atmratio
    df['ATM_D_RATIO'] = atmdratio
    return df

df = populate_credit_card_features(df)


::Started adding credit card balance to dataframe::


In [54]:
bureau = open( root_b + "\\bureau.csv",'r')

def add_merged_features(bureau , df1):
    b_cols = ['SK_ID_CURR','DAYS_CREDIT','CREDIT_DAY_OVERDUE','DAYS_CREDIT_ENDDATE','AMT_ANNUITY',
              'DAYS_ENDDATE_FACT','AMT_CREDIT_MAX_OVERDUE','CNT_CREDIT_PROLONG','AMT_CREDIT_SUM',
              'AMT_CREDIT_SUM_DEBT','AMT_CREDIT_SUM_LIMIT','AMT_CREDIT_SUM_OVERDUE','DAYS_CREDIT_UPDATE'
            ]
    df_bureau = pd.read_csv(bureau, usecols=b_cols)
    df_bureau.replace(np.nan, 0, inplace=True)
    df_bureau = df_bureau.groupby(['SK_ID_CURR'], as_index=True )['DAYS_CREDIT','CREDIT_DAY_OVERDUE','DAYS_CREDIT_ENDDATE','AMT_ANNUITY',
              'DAYS_ENDDATE_FACT','AMT_CREDIT_MAX_OVERDUE','CNT_CREDIT_PROLONG','AMT_CREDIT_SUM',
              'AMT_CREDIT_SUM_DEBT','AMT_CREDIT_SUM_LIMIT','AMT_CREDIT_SUM_OVERDUE','DAYS_CREDIT_UPDATE'].mean().reset_index()
    
    df1 = df1.merge(df_bureau, on='SK_ID_CURR', how='left')
    
    credit_card = open(root_cc + "\\credit_card_balance.csv", 'r')
    c_cols = ['SK_ID_CURR','MONTHS_BALANCE','AMT_BALANCE','AMT_CREDIT_LIMIT_ACTUAL','AMT_DRAWINGS_ATM_CURRENT',
              'AMT_DRAWINGS_CURRENT','AMT_DRAWINGS_OTHER_CURRENT','AMT_DRAWINGS_POS_CURRENT','AMT_INST_MIN_REGULARITY',
              'AMT_PAYMENT_CURRENT','AMT_PAYMENT_TOTAL_CURRENT','AMT_RECEIVABLE_PRINCIPAL','AMT_RECIVABLE','AMT_TOTAL_RECEIVABLE',
              'CNT_DRAWINGS_ATM_CURRENT','CNT_DRAWINGS_CURRENT','CNT_DRAWINGS_OTHER_CURRENT','CNT_DRAWINGS_POS_CURRENT','CNT_INSTALMENT_MATURE_CUM','SK_DPD',
              'SK_DPD_DEF']
    
    df_cc = pd.read_csv(credit_card, usecols=c_cols)
    df_cc.replace(np.nan, 0, inplace=True)
    df_cc = df_cc.groupby(['SK_ID_CURR'], as_index=True )['MONTHS_BALANCE','AMT_BALANCE','AMT_CREDIT_LIMIT_ACTUAL','AMT_DRAWINGS_ATM_CURRENT',
              'AMT_DRAWINGS_CURRENT','AMT_DRAWINGS_OTHER_CURRENT','AMT_DRAWINGS_POS_CURRENT','AMT_INST_MIN_REGULARITY',
              'AMT_PAYMENT_CURRENT','AMT_PAYMENT_TOTAL_CURRENT','AMT_RECEIVABLE_PRINCIPAL','AMT_RECIVABLE','AMT_TOTAL_RECEIVABLE',
              'CNT_DRAWINGS_ATM_CURRENT','CNT_DRAWINGS_CURRENT','CNT_DRAWINGS_OTHER_CURRENT','CNT_DRAWINGS_POS_CURRENT','CNT_INSTALMENT_MATURE_CUM','SK_DPD',
              'SK_DPD_DEF'].mean().reset_index()
    
    df1 = df1.merge(df_cc, on='SK_ID_CURR', how='left')
    
    pos_cols = ['SK_ID_CURR','MONTHS_BALANCE','CNT_INSTALMENT','CNT_INSTALMENT_FUTURE','NAME_CONTRACT_STATUS',
     'SK_DPD','SK_DPD_DEF','NAME_CONTRACT_STATUS']
    pos = open(root + "\\POS_CASH_balance.csv", 'r')
    df_pos = pd.read_csv(pos, usecols=pos_cols)
    df_pos['NAME_CONTRACT_STATUS'] = df_pos['NAME_CONTRACT_STATUS'].map({'Active': -1, 'Approved': 1, 'Canceled': 10,
                                                           'Completed': 100, 'Demand': 1000,
                                                           'Returned to the store': -100,'Signed':-1000})
    
    df_pos.replace(np.nan, 0, inplace=True)
    print(df_pos['NAME_CONTRACT_STATUS'].unique())
    df_pos = df_pos.groupby(['SK_ID_CURR'], as_index=True )['MONTHS_BALANCE','CNT_INSTALMENT',
                                       'CNT_INSTALMENT_FUTURE','NAME_CONTRACT_STATUS'].mean().reset_index()
    
    df1 = df1.merge(df_pos, on='SK_ID_CURR', how='left')
    
    inst_cols = ['SK_ID_CURR','NUM_INSTALMENT_VERSION',
                 'NUM_INSTALMENT_NUMBER','DAYS_INSTALMENT',
                 'DAYS_ENTRY_PAYMENT','AMT_INSTALMENT','AMT_PAYMENT']
    df_inst = pd.read_csv(inst, usecols=inst_cols)
    df_inst.replace(np.nan, 0, inplace=True)
    df_inst = df_inst.groupby(    inst = open(root + "\\installments_payments.csv", 'r')
['SK_ID_CURR'], as_index=True )['NUM_INSTALMENT_VERSION','NUM_INSTALMENT_NUMBER','DAYS_INSTALMENT',
            'DAYS_ENTRY_PAYMENT','AMT_INSTALMENT','AMT_PAYMENT'].mean().reset_index()
    
    df1 = df1.merge(df_inst, on='SK_ID_CURR', how='left')
    return df1
df = add_merged_features(bureau, df)
bureau.close()



[   -1.   100. -1000.     1.  -100.  1000.    10.     0.]


In [55]:
overdue = 0
balance = 0 
atm = 0
atm_d = 0
refused1 =0
cancelled1 = 0
refusedtype1 = 0
cancelledtype1 = 0 
print(df.columns)

for i, row in df.iterrows():
    if df.at[i,'BALANCE_RATIO'] > 0.0:
        balance = balance + 1
    if df.at[i,'AMT_CREDIT_MAX_OVERDUE_1'] > 0.0:
        overdue = overdue + 1 
    if df.at[i,'ATM_RATIO'] > 0.0:
        atm = atm + 1
    if df.at[i,'ATM_RATIO'] > 0.0:
        atm_d = atm_d + 1
    if df.at[i,'REFUSED'] > 0.0:
        refused1 = refused1 + 1 
    if df.at[i,'REFUSED_TYPE'] > 0.0:
        refusedtype1 = refusedtype1 + 1
    if df.at[i,'CANCELLED'] > 0.0:
        cancelled1 = cancelled1 + 1
    if df.at[i,'CANCELLED_TYPE'] > 0.0:
        cancelledtype1 = cancelledtype1 + 1
print(overdue,atm,atm_d,balance, refused1, cancelled1, cancelledtype1, refusedtype1)

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY_x',
       ...
       'MONTHS_BALANCE_y', 'CNT_INSTALMENT', 'CNT_INSTALMENT_FUTURE',
       'NAME_CONTRACT_STATUS', 'NUM_INSTALMENT_VERSION',
       'NUM_INSTALMENT_NUMBER', 'DAYS_INSTALMENT', 'DAYS_ENTRY_PAYMENT',
       'AMT_INSTALMENT', 'AMT_PAYMENT'],
      dtype='object', length=101)


70440 59394 59394 59572 100294 110726 95000 57203


In [56]:
import numpy as np

df = df.sample(frac=1)
#df = df.drop(['NAME_CONTRACT_TYPE'],axis=1,inplace=False)

size = df.__len__()
print(size)
partition_index=int(0.9*size)

train = df.iloc[:partition_index]
train_labels= train['TARGET']
train = train.drop(['SK_ID_CURR','TARGET'], axis=1, inplace=False)
print(train.columns.values)
print(len(train.columns.values))
print('Rows in Training Set '+ str(train.__len__()))

test = df.iloc[partition_index+1:]
test_labels=test['TARGET']
test = test.drop(['SK_ID_CURR','TARGET'], axis=1, inplace=False)
print('Length of test set is::' +str(test.__len__()))

307511


['NAME_CONTRACT_TYPE' 'CODE_GENDER' 'FLAG_OWN_CAR' 'FLAG_OWN_REALTY'
 'CNT_CHILDREN' 'AMT_INCOME_TOTAL' 'AMT_CREDIT' 'AMT_ANNUITY_x'
 'AMT_GOODS_PRICE' 'NAME_TYPE_SUITE' 'NAME_INCOME_TYPE'
 'NAME_EDUCATION_TYPE' 'NAME_FAMILY_STATUS' 'NAME_HOUSING_TYPE'
 'REGION_POPULATION_RELATIVE' 'DAYS_BIRTH' 'DAYS_EMPLOYED'
 'DAYS_REGISTRATION' 'DAYS_ID_PUBLISH' 'OWN_CAR_AGE' 'FLAG_PHONE'
 'OCCUPATION_TYPE' 'CNT_FAM_MEMBERS' 'REGION_RATING_CLIENT'
 'REGION_RATING_CLIENT_W_CITY' 'REG_CITY_NOT_LIVE_CITY'
 'REG_CITY_NOT_WORK_CITY' 'LIVE_CITY_NOT_WORK_CITY' 'ORGANIZATION_TYPE'
 'EXT_SOURCE_1' 'EXT_SOURCE_2' 'EXT_SOURCE_3' 'APARTMENTS_AVG'
 'BASEMENTAREA_AVG' 'YEARS_BEGINEXPLUATATION_AVG' 'YEARS_BUILD_AVG'
 'COMMONAREA_AVG' 'ELEVATORS_AVG' 'YEARS_BUILD_MODE' 'APARTMENTS_MEDI'
 'YEARS_BEGINEXPLUATATION_MEDI' 'LANDAREA_MEDI'
 'AMT_REQ_CREDIT_BUREAU_HOUR' 'AMT_REQ_CREDIT_BUREAU_DAY'
 'AMT_REQ_CREDIT_BUREAU_WEEK' 'AMT_REQ_CREDIT_BUREAU_MON'
 'AMT_REQ_CREDIT_BUREAU_QRT' 'AMT_REQ_CREDIT_BUREAU_YEAR'
 'PREVIOUS

In [57]:
from sklearn.ensemble import RandomForestRegressor
train.replace(np.nan, 0, inplace=True)
regressor = RandomForestRegressor(n_estimators = 100, n_jobs=-1, max_depth = 15,
            max_features=20,random_state=42,
        min_samples_leaf=20, min_samples_split=20)
regressor.fit(train, train_labels)



RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=15,
           max_features=20, max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=20,
           min_samples_split=20, min_weight_fraction_leaf=0.0,
           n_estimators=100, n_jobs=-1, oob_score=False, random_state=42,
           verbose=0, warm_start=False)

In [44]:
test.replace(np.nan, 0, inplace=True)
results = regressor.predict(test)

import sklearn
i=0
correct=0
incorrect=0
ov_correct=0
ov_incorrect=0
golden_num = 0.19

for item in results:
    if(item > golden_num):
        if test_labels.iloc[i] == 1.0:
            #print("Correclty Found a loan record to block!!!!!!")
            correct = correct+1
        else:
            #print("Incorrectly Found a loan record to block!!!!!! "+ str(test_labels.iloc[i]))
            incorrect = incorrect+1
        results[i] = 1
    else:
        results[i] = 0
    if (item <= golden_num and test_labels.iloc[i] == 1) or (item > golden_num and test_labels.iloc[i] == 0):
        ov_incorrect = ov_incorrect + 1
    else :
        ov_correct = ov_correct + 1
    i=i+1

rounded_results = np.array(results)
rounded_results = rounded_results.round().astype(int)
accuracy = sklearn.metrics.accuracy_score(np.array(test_labels), 
                                    rounded_results , normalize=False)

total_rejects = list(test_labels).count(1)
print('Number of loan approvals in data :: '+str(list(test_labels).count(0)))
print('Number of loan denials in data :: '+str(total_rejects))


print("Correct Rejects:: "+ str(correct))
print("Incorrect Rejects:: " + str(incorrect))
print("Recall:: ",correct/total_rejects)
print("Correct Prediction:: " + str(ov_correct))
print("Incorrect Prediction:: " + str(ov_incorrect))
print("Accuracy of model is ::", ov_correct/(ov_correct+ov_incorrect))

print(regressor.feature_importances_)
print(regressor.n_features_)
print(train.columns.values)





Number of loan approvals in data :: 28247
Number of loan denials in data :: 2504
Correct Rejects:: 758
Incorrect Rejects:: 1959
Recall::  0.3027156549520767
Correct Prediction:: 27046
Incorrect Prediction:: 3705
Accuracy of model is :: 0.8795161132971285


[3.14564816e-04 9.38450731e-03 1.55261847e-03 1.68545244e-03
 1.80480683e-03 1.44420510e-02 1.77598482e-02 2.76329558e-02
 1.38375305e-02 1.28410817e-03 5.38857383e-03 5.10631638e-03
 4.21760709e-03 1.48462354e-03 1.79747430e-02 3.83681662e-02
 2.71479943e-02 2.56344110e-02 2.63910166e-02 6.44614759e-03
 1.03982799e-03 9.53045137e-03 2.73869878e-03 1.55607873e-03
 1.63179882e-03 1.40084076e-03 1.78943747e-03 1.18511747e-03
 1.20564033e-02 2.97911466e-02 1.40432916e-01 1.18033972e-01
 3.55399555e-03 4.08108955e-03 3.84116634e-03 1.61056976e-03
 2.96788501e-03 9.22367200e-04 1.59534917e-03 3.29963660e-03
 3.87846328e-03 4.53212699e-03 4.00818194e-06 3.61178310e-05
 8.91073958e-05 5.61704082e-04 8.71991042e-04 4.69404612e-03
 4.04347888e-05 4.77530046e-03 1.18429877e-03 1.27202169e-03
 7.35486080e-03 7.80389757e-03 6.53444818e-03 3.49768150e-03
 2.83994436e-03 1.87434173e-02 1.08394983e-04 1.99747066e-02
 4.98343874e-03 1.16043105e-02 7.38599788e-03 3.30463196e-04
 2.12010050e-02 2.369940

In [45]:

modelfile = 'C:\\Users\\Apurva\\Downloads\\courses\\credit-risk-challenge\\models\\credit_risk_model_v5.sav'
import pickle
pickle.dump(regressor, open(modelfile, 'wb'))



Transform each feature in test data

In [46]:
root_test="C:\\Users\\Apurva\\Downloads\\courses\\credit-risk-challenge\\data\\application_test"
test = open( root_test + "\\application_test.csv",'r')

test_fields = ['SK_ID_CURR','NAME_CONTRACT_TYPE','CODE_GENDER','FLAG_OWN_CAR','FLAG_OWN_REALTY'
          ,'CNT_CHILDREN','AMT_INCOME_TOTAL','AMT_CREDIT','AMT_ANNUITY','AMT_GOODS_PRICE',
          'NAME_TYPE_SUITE','NAME_INCOME_TYPE','NAME_EDUCATION_TYPE','NAME_FAMILY_STATUS',
          'NAME_HOUSING_TYPE','REGION_POPULATION_RELATIVE','DAYS_BIRTH','DAYS_EMPLOYED'
          ,'DAYS_REGISTRATION','DAYS_ID_PUBLISH','OWN_CAR_AGE','FLAG_PHONE','OCCUPATION_TYPE',
          'CNT_FAM_MEMBERS','REGION_RATING_CLIENT','REGION_RATING_CLIENT_W_CITY',
          'REG_CITY_NOT_LIVE_CITY','REG_CITY_NOT_WORK_CITY','ORGANIZATION_TYPE',
          'LIVE_CITY_NOT_WORK_CITY','APARTMENTS_AVG','BASEMENTAREA_AVG',
          'YEARS_BEGINEXPLUATATION_AVG','YEARS_BUILD_AVG','EXT_SOURCE_1','EXT_SOURCE_2'
           ,'EXT_SOURCE_3', 'AMT_REQ_CREDIT_BUREAU_YEAR','YEARS_BEGINEXPLUATATION_AVG',
          'APARTMENTS_AVG','YEARS_BUILD_AVG','COMMONAREA_AVG','ELEVATORS_AVG','YEARS_BUILD_MODE',
          'APARTMENTS_MEDI','YEARS_BEGINEXPLUATATION_MEDI','LANDAREA_MEDI','AMT_REQ_CREDIT_BUREAU_HOUR',
          'AMT_REQ_CREDIT_BUREAU_DAY','AMT_REQ_CREDIT_BUREAU_WEEK','AMT_REQ_CREDIT_BUREAU_MON',
          'AMT_REQ_CREDIT_BUREAU_QRT']

dftest = pd.read_csv(test, usecols=test_fields)
dftest.replace(np.nan, 0, inplace=True)
import numpy as np

dftest = initital_cleaning(dftest)
dftest = populate_bureau_features(dftest)
dftest = populate_credit_card_features(dftest)

bureau = open( root_b + "\\bureau.csv",'r')
dftest = add_merged_features(bureau, dftest)

dftest1 = dftest.drop(['SK_ID_CURR'], axis=1, inplace=False)


['Cash loans' 'Revolving loans']
['F' 'M']
['N' 'Y']
['Y' 'N']
['Unaccompanied' 0 'Family' 'Spouse, partner' 'Group of people' 'Other_B'
 'Children' 'Other_A']
['Working' 'State servant' 'Pensioner' 'Commercial associate'
 'Businessman' 'Student' 'Unemployed']
['Higher education' 'Secondary / secondary special' 'Incomplete higher'
 'Lower secondary' 'Academic degree']
['Married' 'Single / not married' 'Civil marriage' 'Widow' 'Separated']
['House / apartment' 'With parents' 'Rented apartment'
 'Municipal apartment' 'Office apartment' 'Co-op apartment']
[0 'Low-skill Laborers' 'Drivers' 'Sales staff' 'High skill tech staff'
 'Core staff' 'Laborers' 'Managers' 'Accountants' 'Medicine staff'
 'Security staff' 'Private service staff' 'Secretaries' 'Cleaning staff'
 'Cooking staff' 'HR staff' 'Waiters/barmen staff' 'Realty agents'
 'IT staff']
['Kindergarten' 'Self-employed' 'Transport: type 3'
 'Business Entity Type 3' 'Government' 'Industry: type 9' 'School'
 'Trade: type 2' 'XNA' 'Servic

[   -1.   100. -1000.     1.  -100.  1000.    10.     0.]


In [48]:
dftest1.replace(np.nan, 0, inplace=True)
results = regressor.predict(dftest1)
test_results = open( root_test + "\\application_results.csv",'w')
test_results.write('SK_ID_CURR,TARGET\n')
for i, row in dftest.iterrows():
    predict = results[i]
    if predict > golden_num:
        predict = 1
    else :
        predict = 0
    test_results.write(str(dftest.at[i, 'SK_ID_CURR']) + ','+ str(predict) + '\n')    
test_results.close()
